name: Build and Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --save-dev @types/express@4.17.6 @types/express-serve-static-core@4.17.6

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
