name: Build and Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository and setup node
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
